import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Poppins as FontSans } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { cn } from "@/lib/utils";
import { SessionProvider } from "next-auth/react";
import Provider from "@/components/Provider";

const fontSans = FontSans({
  weight:['200','300','400','500','100','600','700',
    '800','900'
  ],
  subsets: ["latin"],
  variable: "--font-sans",
});

// const inter = Po({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: process.env.APP_NAME || "Default Title",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <meta name="viewport" content="width=1366, initial-scale=1" /> */}
      <body className={fontSans.className}>
        <Toaster position="bottom-right" toastOptions={{
          success:{
            style:{
              backgroundColor:'#E0E5F5',
              border:'1px solid gray',
              borderRadius:'2px'
            },
            icon: undefined,
            iconTheme:{
              primary:'#444',
              secondary:'#fff'
            }
          },
          error:{
            style:{
              backgroundColor:'#E0E5F5',
              border:'1px solid gray',
              borderRadius:'2px',
              height:'40px',
              fontSize:'12px'
            },
            icon: undefined,
            iconTheme:{
              primary:'#444',
              secondary:'#fff'
            }
          }
        }} />
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
